pipeline {
    agent any
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "jenkins-maven"
    }
    environment {
        // Define environment variables
        DOCKER_REPO = 'Klash23'
        DOCKER_IMAGE = 'jdk'
    }
    stages {
        stage('Build') {
            steps {
                git 'https://github.com/Klash23/javaprojects'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                success {
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                // Build Docker image from the artifact
                sh "docker build -t ${DOCKER_REPO}/${DOCKER_IMAGE} ."
            }
        }
        stage('Push Docker Image') {
            steps {
                // Log in to Docker Hub (assuming you're using Docker Hub)
                withCredentials([usernamePassword(credentialsId: 'docker1', usernameVariable: 'Username', passwordVariable: 'Password')]) {
                    sh "docker login -u $Username -p $Password"
                }

                // Push Docker image to Docker Hub
                sh "docker push ${DOCKER_REPO}/${DOCKER_IMAGE}"
            }
        }
    }
}
